// Curated celebrity/creator travel spots. Photos are Unsplash CDN URLs.
// Hand-maintained for now; can be swapped for a real feed later.

export interface CelebritySpot {
  name: string;     // 장소 이름
  note: string;     // why / what happened there
}

export interface CelebrityDestination {
  id: string;
  person: string;
  city: string;               // 표시용 "도시, 나라"
  countryCode?: string;       // 내부 매핑용 (없을 수도)
  photo: string;              // 와이드 랜드스케이프 Unsplash URL
  gallery?: string[];         // 추가 사진들
  caption: string;            // 한 줄 컨텍스트
  tag?: string;               // 🎬 콘텐츠 / 📸 화보 ...
  year?: number;              // 다녀온 해
  duration?: string;          // 예: "5박 6일"
  summary: string;            // 2~3문장 배경 설명
  spots: CelebritySpot[];     // 방문한 주요 장소들
  tips?: string[];            // 팬·여행자 팁
  style?: string;             // 여행 분위기 키워드 (해시태그 스타일)
  source?: { label: string; url?: string }; // 참고 출처
}

export const CELEBRITY_DESTINATIONS: CelebrityDestination[] = [
  {
    id: 'jennie-santorini',
    person: '제니 (BLACKPINK)',
    city: '산토리니, 그리스',
    countryCode: 'GR',
    photo: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1507501336603-6e31db2be093?w=900&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=900&q=80&auto=format&fit=crop',
    ],
    caption: '화보 촬영으로 다녀온 에게해의 석양',
    tag: '📸 화보',
    year: 2024,
    duration: '4박 5일',
    summary: '브랜드 캠페인 화보 촬영을 겸한 휴가. 이아 마을의 푸른 돔과 해넘이를 배경으로 한 촬영이 SNS에서 폭발적 반응을 얻음.',
    spots: [
      { name: '이아 선셋 포인트', note: '캘더라를 배경으로 한 골든아워 촬영' },
      { name: '아모이 호텔', note: '스위트 풀이 있는 부티크 호텔' },
      { name: '아모이 카페', note: '아침 식사와 요거트 프레스코' },
      { name: '레드 비치', note: '화산 지형의 붉은 절벽' },
    ],
    tips: ['이아는 일몰 1시간 전에 자리 잡아야 함', '렌터카 대신 4륜 ATV가 골목에서 편리'],
    style: '#해넘이 #화이트블루 #리조트',
    source: { label: '공식 인스타 포스팅 참고' },
  },
  {
    id: 'rm-berlin',
    person: 'RM (BTS)',
    city: '베를린, 독일',
    countryCode: 'DE',
    photo: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=1200&q=80&auto=format&fit=crop',
    caption: '개인 투어 — 박물관섬과 미테 지구의 갤러리',
    tag: '🎨 아트',
    year: 2023,
    duration: '6일 단독 여행',
    summary: '입대 전 휴식을 겸한 아트 여행. 박물관섬 전체를 패스로 돌고 현대미술관·사립 갤러리까지 탐방. 미테 지구 로컬 레스토랑 리뷰가 화제.',
    spots: [
      { name: '페르가몬 박물관', note: '이슈타르 문 앞에서 오랫동안 머묾' },
      { name: 'Hamburger Bahnhof', note: '현대미술관 — Beuys 섹션 중점' },
      { name: '쾨니히 갤러리', note: '현대 조각 전시' },
      { name: 'Mitte 스트리트푸드', note: '커리부어스트와 도너 순회' },
    ],
    tips: ['뮤지엄패스 3일권이 가장 경제적', '월요일은 많은 박물관 휴관'],
    style: '#아트 #갤러리호핑 #로컬푸드',
    source: { label: 'RM 개인 인스타 참고' },
  },
  {
    id: 'cha-kyoto',
    person: '차은우',
    city: '교토, 일본',
    countryCode: 'JP',
    photo: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80&auto=format&fit=crop',
    caption: '아라시야마 대나무숲·기온 거리 브이로그',
    tag: '🎬 콘텐츠',
    year: 2024,
    duration: '3박 4일',
    summary: '팬 콘텐츠 촬영 겸 힐링 여행. 새벽 대나무숲과 기온의 게이샤 거리가 담긴 브이로그 조회수 1,000만 돌파.',
    spots: [
      { name: '아라시야마 대나무숲', note: '새벽 6시 촬영 — 관광객 없음' },
      { name: '기온 하나미코지', note: '전통 찻집과 게이샤 관찰' },
      { name: '후시미 이나리', note: '천 개의 붉은 도리이 등반' },
      { name: '긴카쿠지', note: '은각사 정원 산책' },
    ],
    tips: ['교토 교통은 원데이 버스패스가 왕도', '기온 포토존은 저녁 6~8시가 베스트'],
    style: '#힐링 #전통 #브이로그',
    source: { label: '본인 유튜브 채널' },
  },
  {
    id: 'aespa-interlaken',
    person: 'aespa',
    city: '인터라켄, 스위스',
    countryCode: 'CH',
    photo: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=1200&q=80&auto=format&fit=crop',
    caption: '알프스 풍경을 배경으로 한 뮤직비디오 로케',
    tag: '🎵 MV',
    year: 2024,
    duration: '7일 일정 중 4일 촬영',
    summary: '타이틀곡 뮤직비디오 촬영을 위해 전원 현지 이동. 융프라우요흐·쉴트호른 정상을 배경으로 한 장면이 K-pop 팬덤 내 "버킷리스트" 트렌드를 만듦.',
    spots: [
      { name: '융프라우요흐', note: '유럽 최고 기차역, MV 라스트신' },
      { name: '쉴트호른', note: '007 영화 촬영지 — 360도 알프스 뷰' },
      { name: '하더쿨름', note: '인터라켄 야경 포인트' },
      { name: '쉴리니헤', note: '트레일 & 산장 점심' },
    ],
    tips: ['스위스트래블패스 8일권이 기차·유람선 포함', '6~8월은 융프라우 일부 구간 우회 필요'],
    style: '#알프스 #하이킹 #MV성지',
    source: { label: 'SM엔터테인먼트 공식 메이킹' },
  },
  {
    id: 'iu-positano',
    person: '아이유',
    city: '포지타노, 이탈리아',
    countryCode: 'IT',
    photo: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80&auto=format&fit=crop',
    caption: '아말피 해안 드라이브와 레몬 카페',
    tag: '📸 화보',
    year: 2023,
    duration: '5박 7일',
    summary: '유럽 콘서트 투어 중 오프데이 2일을 더해 만든 로드 트립. 아말피·포지타노·라벨로 이어지는 절벽 드라이브가 팬북 표지로 사용됨.',
    spots: [
      { name: '포지타노 해변', note: '파스텔 건물과 절벽 조합' },
      { name: '라벨로 빌라 루폴로', note: '정원에서 내려다본 바다' },
      { name: '아말피 두오모', note: '계단 앞 포토존' },
      { name: 'Da Adolfo', note: '보트로만 가는 해변 식당' },
    ],
    tips: ['아말피 해안은 렌트카보다 기사 포함 차량 추천', '여름 성수기엔 2~3개월 전 숙소 확정'],
    style: '#지중해 #드라이브 #파스텔',
    source: { label: 'IU 8집 콘서트 화보' },
  },
  {
    id: 'jisoo-paris',
    person: '지수 (BLACKPINK)',
    city: '파리, 프랑스',
    countryCode: 'FR',
    photo: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80&auto=format&fit=crop',
    caption: '디올 하우스 투어와 마레 지구 산책',
    tag: '👗 패션',
    year: 2024,
    duration: '4박 5일 (패션위크)',
    summary: '디올 글로벌 앰버서더로 파리 패션위크 참석. 디올 30 몽테뉴 본사와 마레 지구에서 포착된 사복 룩이 전 세계 패션 매체에 실림.',
    spots: [
      { name: '디올 30 몽테뉴', note: '하우스 뮤지엄 & 쇼' },
      { name: '마레 지구', note: '빈티지 숍과 카페 투어' },
      { name: '팔레 드 도쿄', note: '현대미술 관람' },
      { name: 'Pierre Hermé', note: '마카롱과 초콜릿' },
    ],
    tips: ['패션위크 기간 호텔은 1년 전부터 품귀', '지수 방문 카페는 평상시 예약 없이도 가능'],
    style: '#패션위크 #사복룩 #카페호핑',
    source: { label: 'Dior 공식 이벤트' },
  },
  {
    id: 'kwaktube-lisbon',
    person: '곽튜브',
    city: '리스본, 포르투갈',
    countryCode: 'PT',
    photo: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80&auto=format&fit=crop',
    caption: '알파마 언덕·28번 트램 현지 유튜브',
    tag: '🎬 유튜브',
    year: 2024,
    duration: '6박 8일',
    summary: '저예산 여행 채널의 유럽 시즌. 28번 트램 라이딩, 파두 라이브, 포르투 와이너리까지 담은 3부작 영상이 합산 500만 뷰.',
    spots: [
      { name: '알파마 전망대', note: '테주강 파노라마' },
      { name: '28번 트램', note: '노란 트램 루트 전체' },
      { name: 'Pastéis de Belém', note: '원조 에그타르트' },
      { name: '포르투 세하 두 필라르', note: '도우루 강과 다리 전망' },
    ],
    tips: ['리스본-포르투 알파 기차 2시간 40분', '트램 28번은 오전 7~9시가 가장 덜 붐빔'],
    style: '#저예산 #로컬 #트램',
    source: { label: '본인 유튜브 채널' },
  },
  {
    id: 'hani-iceland',
    person: '하니 (NewJeans)',
    city: '레이캬비크, 아이슬란드',
    countryCode: 'IS',
    photo: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=1200&q=80&auto=format&fit=crop',
    caption: '오로라 · 블루라군 화보 로드트립',
    tag: '📸 화보',
    year: 2024,
    duration: '5박 7일',
    summary: '앨범 프리릴리즈 화보를 위한 겨울 촬영. 링로드 일부 구간을 따라 폭포·빙하·온천을 찍은 시네마틱 사진이 컨셉 비주얼로 공개됨.',
    spots: [
      { name: '블루라군', note: '실리카 얼굴팩 리추얼' },
      { name: '그들린 폭포', note: '얼음 낀 폭포 포토존' },
      { name: '레이니스파우라 블랙샌드', note: '검은 해변' },
      { name: '오로라 헌팅 투어', note: '비크 근교 개활지' },
    ],
    tips: ['오로라는 10월~3월 구름예보 확인이 핵심', '4륜 구동 필수 — 강풍으로 문짝 파손 흔함'],
    style: '#겨울 #오로라 #시네마틱',
    source: { label: 'ADOR 공식 화보' },
  },
  {
    id: 'chim-dubai',
    person: '침착맨',
    city: '두바이, UAE',
    countryCode: 'AE',
    photo: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop',
    caption: '부르즈 할리파·사막 사파리 현지 방송',
    tag: '🎬 콘텐츠',
    year: 2023,
    duration: '4박 5일',
    summary: '설 연휴 특집 생방송. 세계 최고층 전망대와 사막 사파리 캠프 1박까지 포함한 편성으로 동시접속 20만 기록.',
    spots: [
      { name: '부르즈 할리파 At The Top', note: '선셋 시간대 예약' },
      { name: 'Al Marmoom 사막 캠프', note: '사륜구동·캠프파이어' },
      { name: '두바이몰 아쿠아리움', note: '실내 대형 수족관' },
      { name: '주메이라 퍼블릭 비치', note: 'Burj Al Arab 조망' },
    ],
    tips: ['사막 사파리는 해질녘 출발 프로그램', '아바야 무료 대여하는 모스크 투어 추천'],
    style: '#럭셔리 #사막 #야경',
    source: { label: '본인 유튜브 라이브' },
  },
  {
    id: 'ana-bali',
    person: '유튜버 아나',
    city: '우붓, 발리',
    countryCode: 'ID',
    photo: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80&auto=format&fit=crop',
    caption: '요가 리트리트·라이스 필드 러닝',
    tag: '🌿 리트리트',
    year: 2024,
    duration: '7박 8일',
    summary: '웰니스 콘텐츠 크리에이터의 연간 리셋 여행. 한달 살기 대신 집약적 리트리트로 바꾼 해. 요가·명상 클래스 후기가 회원가입 폭증으로 이어짐.',
    spots: [
      { name: '요가반 Ubud', note: '아침 빈야사 + 비건 브런치' },
      { name: '떠갈랄랑 라이스테라스', note: '일출 러닝 코스' },
      { name: '캠푸한 릿지 워크', note: '1시간 걷기 명상' },
      { name: 'Alchemy', note: '로우비건 카페' },
    ],
    tips: ['우붓은 우버 대신 GoJek 사용', '아침 6시 전 라이스필드는 관광객 0명'],
    style: '#리트리트 #요가 #웰니스',
    source: { label: '본인 인스타/유튜브' },
  },
  {
    id: 'songkang-tokyo',
    person: '송강',
    city: '도쿄, 일본',
    countryCode: 'JP',
    photo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80&auto=format&fit=crop',
    caption: '드라마 프로모션 중 사복 투어',
    tag: '🎬 콘텐츠',
    year: 2024,
    duration: '3박 4일',
    summary: '아시아 팬미팅 투어 중 하루 오프데이를 활용한 사복 산책. 시부야 스카이·하라주쿠 빈티지 숍에서 포착된 패션이 K-패션 매체에 실림.',
    spots: [
      { name: '시부야 스카이', note: '오픈 에어 전망대' },
      { name: '하라주쿠 캣 스트리트', note: '빈티지 편집숍 투어' },
      { name: '나카메구로', note: '강변 산책·카페' },
      { name: '도쿄타워 라이팅', note: '저녁 블루아워 촬영' },
    ],
    tips: ['시부야 스카이는 야경 1시간 전 예약', '사복 투어는 평일 오전 한정'],
    style: '#사복 #빈티지 #야경',
    source: { label: '팬 SNS 포착' },
  },
  {
    id: 'wonyoung-paris',
    person: '장원영 (IVE)',
    city: '파리, 프랑스',
    countryCode: 'FR',
    photo: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80&auto=format&fit=crop',
    caption: '미우미우 쇼 참석 · 몽마르뜨 사색',
    tag: '👗 패션',
    year: 2024,
    duration: '5일',
    summary: '미우미우 글로벌 앰배서더 자격으로 패션위크 메인쇼 참석. 일정 사이에 몽마르뜨와 퐁네프를 산책한 "장원영 루틴" 영상이 틱톡 바이럴.',
    spots: [
      { name: '미우미우 SS 쇼장', note: 'Palais d\'Iéna' },
      { name: '몽마르뜨 사크레쾨르', note: '파리 시내 파노라마' },
      { name: '퐁네프 다리', note: '노을 산책' },
      { name: 'Angelina', note: '핫초콜릿·몽블랑' },
    ],
    tips: ['사크레쾨르 계단은 저녁 6시가 덜 붐빔', '앙젤리나 오리지널 지점은 Rivoli'],
    style: '#패션위크 #파리지앵 #몽마르뜨',
    source: { label: 'Miu Miu 공식' },
  },
  {
    id: 'gcoo-newyork',
    person: '슈카월드',
    city: '뉴욕, 미국',
    countryCode: 'US',
    photo: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&q=80&auto=format&fit=crop',
    caption: '월가·브루클린 브리지 경제 방송',
    tag: '🎬 콘텐츠',
    year: 2024,
    duration: '5박 7일',
    summary: '경제 유튜브 특별편. 월가 투어 + 브루클린 브리지 위 야외 방송으로 시청자 50만 몰림. 경제 이야기에 여행기가 얹혀 시너지.',
    spots: [
      { name: '월스트리트·NYSE', note: '증권거래소 앞 브레이퀀드' },
      { name: '브루클린 브리지', note: '새벽 도보 크로싱' },
      { name: 'One World Observatory', note: '하늘에서 본 맨해튼' },
      { name: 'Katz\'s Deli', note: '파스트라미 샌드위치' },
    ],
    tips: ['지하철 OMNY 컨택리스 결제가 가장 빠름', '브루클린 브리지는 해 뜨기 30분 전 출발'],
    style: '#경제투어 #도시산책 #야경',
    source: { label: '본인 유튜브 채널' },
  },
  {
    id: 'tae-bangkok',
    person: '태연',
    city: '방콕, 태국',
    countryCode: 'TH',
    photo: 'https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?w=1200&q=80&auto=format&fit=crop',
    caption: '월드투어 오프데이 — 왓아룬·루프탑',
    tag: '🎵 MV',
    year: 2024,
    duration: '3일',
    summary: '아시아 월드투어 중 오프데이 3일을 방콕에서. 팬들이 공유한 "태연이 간 루프탑" 지도가 커뮤니티에서 화제.',
    spots: [
      { name: '왓아룬', note: '해질녘 대불탑' },
      { name: 'Vertigo Too', note: '61층 루프탑 바' },
      { name: '짜오프라야 강 디너크루즈', note: '재즈 라이브' },
      { name: '짜뚜짝 주말시장', note: '디자인 숍' },
    ],
    tips: ['BTS 스카이트레인 원데이 패스 150바트', '루프탑은 드레스코드 확인 필수'],
    style: '#루프탑 #크루즈 #쇼핑',
    source: { label: 'SM엔터테인먼트' },
  },
  {
    id: 'lisa-phuket',
    person: '리사 (BLACKPINK)',
    city: '푸켓·코피피, 태국',
    countryCode: 'TH',
    photo: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&q=80&auto=format&fit=crop',
    caption: '본가 방문 후 코피피 보트 투어',
    tag: '📸 화보',
    year: 2024,
    duration: '7일 (본가 포함)',
    summary: '부모님 방문 후 솔로 활동 재충전 목적의 섬 여행. 피피 레·마야베이 수영 영상이 태국 관광청 공식 캠페인으로 이어짐.',
    spots: [
      { name: '마야베이', note: '아침 첫 배 — 인파 없음' },
      { name: '피피돈 빌리지', note: '해변가 카페' },
      { name: '팡응아 베이', note: '석회암 바위 카약' },
      { name: '라야 야이', note: '고급 리조트 휴식' },
    ],
    tips: ['마야베이는 일일 방문자 수 제한', '피피 보트투어는 전날 예약이 안전'],
    style: '#섬 #보트투어 #화보',
    source: { label: '본인 인스타' },
  },
  {
    id: 'winter-hongkong',
    person: '윈터 (aespa)',
    city: '홍콩, 중국 특별행정구',
    countryCode: 'HK',
    photo: 'https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=1200&q=80&auto=format&fit=crop',
    caption: '빅토리아 피크 · 센트럴 쇼핑',
    tag: '👗 패션',
    year: 2023,
    duration: '3박 4일',
    summary: '브랜드 팝업 오픈 참석차 방문. 피크트램과 침사추이 야경 속 사복 룩이 팬들에게 "힙홍콩 스타일"로 회자됨.',
    spots: [
      { name: '빅토리아 피크', note: '피크트램 타고 올라' },
      { name: '침사추이 프롬나드', note: '심포니 오브 라이트 8시' },
      { name: 'IFC 몰', note: '팝업 스토어 참석' },
      { name: 'Tim Ho Wan', note: '딤섬' },
    ],
    tips: ['옥토퍼스 카드 한 장이면 교통·편의점 다 해결', '피크트램은 온라인 예약이 줄 서기 절반'],
    style: '#야경 #쇼핑 #딤섬',
    source: { label: '팬 SNS' },
  },
  {
    id: 'hyun-marrakech',
    person: '박신혜',
    city: '마라케시, 모로코',
    countryCode: 'MA',
    photo: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1200&q=80&auto=format&fit=crop',
    caption: '여행 예능 — 메디나 바자르 투어',
    tag: '🎬 예능',
    year: 2024,
    duration: '6박 8일',
    summary: '여행 리얼리티 프로그램 해외편. 마라케시의 메디나 시장과 아틀라스 산맥 1박 캠핑이 시청률 급등을 이끔.',
    spots: [
      { name: '제마 엘프나 광장', note: '저녁 라이브 공연·야시장' },
      { name: '마조렐 정원', note: 'YSL 블루로 유명' },
      { name: 'Ait Ben Haddou', note: '영화 촬영지 (글래디에이터)' },
      { name: 'Atlas Mountain 베르베르 가옥', note: '홈스테이 저녁식사' },
    ],
    tips: ['사하라 투어는 최소 2박 3일 필요', '시장에선 부르는 가격의 1/3부터 흥정'],
    style: '#사하라 #메디나 #베르베르',
    source: { label: '여행 예능 공식' },
  },
  {
    id: 'joo-queenstown',
    person: '주우재',
    city: '퀸스타운, 뉴질랜드',
    countryCode: 'NZ',
    photo: 'https://images.unsplash.com/photo-1469521669194-babb45599def?w=1200&q=80&auto=format&fit=crop',
    caption: '번지점프·스카이다이빙 챌린지',
    tag: '🎬 예능',
    year: 2023,
    duration: '5박 7일',
    summary: '예능 채널 액티비티 스페셜. 카와라우 번지 + 스카이다이빙 + 제트보트 3종세트를 하루에 몰아친 편집이 1주 만에 조회수 800만 돌파.',
    spots: [
      { name: 'Kawarau Bridge 번지', note: '세계 최초 상업 번지 포인트 43m' },
      { name: 'Nzone 스카이다이빙', note: '해발 1만 5000피트' },
      { name: 'Shotover Jet', note: '협곡 제트보트' },
      { name: 'Fergburger', note: '세계에서 가장 유명한 수제버거' },
    ],
    tips: ['Nomad Adventure 콤보권이 20% 저렴', '스카이다이빙은 예약 후 날씨로 2~3회 리스케줄 흔함'],
    style: '#익스트림 #액티비티 #대자연',
    source: { label: '유튜브 채널' },
  },
  {
    id: 'yumi-havana',
    person: '이효리',
    city: '아바나, 쿠바',
    countryCode: 'CU',
    photo: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=1200&q=80&auto=format&fit=crop',
    caption: '부에나비스타 소셜 클럽 라이브 녹음',
    tag: '🎵 음악',
    year: 2023,
    duration: '7일',
    summary: '음반 프로젝트 녹음 겸 가족 여행. 올드 아바나의 쿠반 재즈 바에서의 깜짝 무대가 현지 방송에 보도.',
    spots: [
      { name: '카사 데 라 무시카', note: '쿠반 살사 라이브' },
      { name: '올드 아바나', note: '유네스코 구시가지' },
      { name: 'Malecón', note: '일몰 드라이브' },
      { name: 'Vedado 올드카 투어', note: '56년식 쉐보레 렌탈' },
    ],
    tips: ['비자·의료보험은 입국 전 필수', '카드 결제 거의 안 됨 — USD 현금 지참'],
    style: '#살사 #올드카 #라틴',
    source: { label: '음반 수록곡 다큐' },
  },
  {
    id: 'tiffany-seoul-day',
    person: '티파니 영',
    city: '서울→부산, 한국',
    countryCode: 'KR',
    photo: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=1200&q=80&auto=format&fit=crop',
    caption: 'KTX 국내 미식 투어',
    tag: '📸 화보',
    year: 2024,
    duration: '3일',
    summary: '라이프스타일 매거진 화보 촬영 겸 국내 단거리 로드. 부산 송정과 해운대, 광안리 야경을 원데이로 누비는 편집이 국내 여행 붐을 일으킴.',
    spots: [
      { name: '송정 서핑 비치', note: '아침 보드' },
      { name: '깡깡이 예술마을', note: '레트로 공방 골목' },
      { name: '광안대교 야경', note: '민락수변공원' },
      { name: 'F1963', note: '복합 문화 공간' },
    ],
    tips: ['KTX 특실 왕복 10만 원대', '부산 원데이 투어는 해운대-광안리 택시 3건이면 충분'],
    style: '#국내 #KTX #야경',
    source: { label: 'Vogue Korea 화보' },
  },
];

// Travel recommendation / advisory banners. Rotates every visit.
export interface TravelAdvisory {
  id: string;
  kind: 'recommend' | 'alert';
  emoji: string;
  title: string;
  body: string;
  cta?: string;
}

export const TRAVEL_ADVISORIES: TravelAdvisory[] = [
  { id: 'rec-taiwan-spring', kind: 'recommend', emoji: '🌸', title: '지금 가기 좋은: 대만', body: '5월 중순까지 비성수기 항공권 40% 저렴. 지우펀·타이난 날씨가 이상적이에요.' },
  { id: 'rec-portugal',      kind: 'recommend', emoji: '🍷', title: '떠오르는 여행지: 포르투갈', body: '유로존 대비 물가 20%↓. 리스본·포르투 중심으로 한국인 방문이 빠르게 늘고 있어요.' },
  { id: 'alert-holiday',     kind: 'alert',     emoji: '⚠️', title: '황금연휴 주의', body: '5월 초·10월 초 연휴 항공권은 평소보다 최대 80% 비싸요. 2주 전까지는 확정하세요.' },
  { id: 'alert-baht-weak',   kind: 'alert',     emoji: '💸', title: '환율 변동', body: '태국 바트·베트남 동은 최근 약세. 현지 결제가 10~15% 저렴해졌어요.' },
  { id: 'rec-hidden-uz',     kind: 'recommend', emoji: '💎', title: '숨은 명소: 우즈베키스탄', body: '사마르칸트 블루 돔과 부하라 올드타운. 비자 면제로 접근성도 좋아요.' },
  { id: 'alert-peak-season', kind: 'alert',     emoji: '🔥', title: '성수기 경고', body: '7~8월 일본·유럽 숙박은 평소의 2배 이상. 예산 여유를 30% 더 두세요.' },
  { id: 'rec-georgia',       kind: 'recommend', emoji: '🏔️', title: '뜨고 있는 여행지: 조지아', body: '트빌리시 올드타운과 카즈베기 산장. 와인·카차푸리 가성비 최고.' },
  { id: 'alert-schengen',    kind: 'alert',     emoji: '🛂', title: '솅겐 출입국 변화', body: 'ETIAS 적용 예정 — 사전 승인 필요. 유럽 6개월 이내 일정은 미리 확인.' },
];
